schema: >-
    definition user {}

    definition industry {
        relation relationship_manager: user
    }
    /**
    * portfolio is an example resource.
    */
    definition portfolio {
        relation portfolio_manager: user
        relation senior_agent: user
        relation associate_agent: user

        relation industry: industry

        permission create = portfolio_manager + industry->relationship_manager
        permission update = create + senior_agent
        
        permission read = create + associate_agent
    }

    /**
    * document is a sub resource of portfolio
    */

    definition document {
        relation parent: portfolio

        permission create = parent->create
        permission update = parent->update
        permission read = parent->update + parent->read + parent->create

    }